name: KeeleCore
version: '1.0'
main: dev.joey.keelecore.KeeleCore
api-version: 1.19
authors: [ Joey ]
description: The Core for the keele server
depend:
  - Vault
  - LuckPerms
website: https://joeyfox.dev

commands:
  gamemode:
    description: Changes the players gamemode
    permission: kc.gamemode
    aliases:
      - gm

  teleport:
    description: Teleports a player
    permission: kc.teleport
    aliases:
      - tp

  time:
    description: Changes the world time
    permission: kc.time
    aliases:
      - tm
      - t

  vanish:
    description: Vanishes a user
    permission: kc.vanish
    aliases:
      - v
      - vn

  whois:
    description: Gains info about a user
    permission: kc.whois
    aliases:
      - ws
      - seen
  god:
    description: Applies godmode to a player
    permission: kc.god

  hub:
    description: Goes to hub
    aliases:
      - lobby

  feed:
    description: Feeds a player
    permission: kc.feed

  heal:
    description: Heals a player
    permission: kc.heal

  clearlag:
    description: clears the server lag
    permission: kc.clearlag

  speed:
    description: Sets flight speed
    permission: kc.speed

  setspawn:
    description: Sets spawnpoint
    permission: kc.setspawn

  spawn:
    description: Teleports to spawn

  rules:
    description: Shows rules
    aliases:
      - rule

  nextclear:
    aliases:
      - nextlag
    description: Shows when next clear lag

  announce:
    aliases:
      - ann
      - announcement
    description: Announces a message to the server
    permission: kc.announce

  discord:
    description: Links our discord