name: CravingChaos
version: '1.0'
main: dev.joeyfox.cravingChaos.CravingChaos
api-version: '1.21'
authors: [Joeyfoxo]
description: Another Furry Plugin
website: https://joeyfox.dev
load: POSTWORLD

depend:
  - KeeleCore