name: KeeleHub
version: '${project.version}'
main: dev.joeyfoxo.keelehub.KeeleHub
api-version: 1.19
authors: [ Joey ]
description: Just Another Furry Hub
website: https://joeyfox.dev

depend: [ KeeleCore ]
softdepend: [ KeeleCore ]