format: "{prefix}{name}{suffix}: {message}"
discord: "https://discord.gg"
spawnWorld: ""

rules:
  - "&c1) &6Do not use Inappropriate Usernames, Skins and Capes"
  - "&c2) &6Do not use any client or modification that provides an unfair advantage over other players"
  - "&c3) &6Do not attempt or use any bugs or exploits to gain unfair advantages"
  - "&c4) &6Do not use multiple accounts to gain an advantage"
  - "&c5) &6Do not make any threats or wishes of harm towards any player or staff member"
  - "&c6) &6Do not impersonate a staff member"
  - "&c7) &6Do not advertise other servers, server IPs, server websites, server stores"
  - "&c8) &6Do not intentionally or unintentionally duplicate items, entities or others"
  - "&c9) &6Do not use or create any building/machine to lag out the server, crash or make the game unplayable for other players."
  - "&c10) &6Do not use any machine/method to load chunks while a player is not in them"
  - "&c11) &6Do not trade in-game items, coordinates, features and such for real money"
  - "&c12) &6Any modifications/software made that can not be done in vanilla Minecraft is not allowed"
  - "&c13) &6Raiding or attempted griefing a claimed base is prohibited"
  - "&c14) &aRaiding chests which are unlocked inside a claim is allowed"

autoAnnounceTimer: -1

autoAnnouncer:
  - "&e&lThis Server is still in BETA please report any bugs or suggestions to: &r&6https://forms.gle/YmKYYSRaUpRDWKaP7"
  - "&e&lPlease ensure you've read the rules"

database:
  host: "localhost"
  port: 3306
  name: "KeeleMC"
  user: "joey"
  password: "nE4p!rTz@X9w#sG2"