name: KeeleCore
version: '${project.version}'
main: dev.joey.keelecore.KeeleCore
api-version: 1.19
authors: [ Joey ]
description: The Core for the keele server
website: https://joeyfox.dev

commands:
  gamemode:
    description: Changes the players gamemode
    aliases:
      - gm

  teleport:
    description: Teleports a player
    aliases:
      - tp

  time:
    description: Changes the world time
    aliases:
      - tm
      - t

  vanish:
    description: Vanishes a user
    aliases:
      - v
      - vn

  whois:
    description: Gains info about a user
    aliases:
      - ws
      - seen
  god:
    description: Applies godmode to a player

  hub:
    description: Goes to hub
    aliases:
      - lobby

  feed:
    description: Feeds a player

  heal:
    description: Heals a player

  clearlag:
    description: clears the server lag

  speed:
    description: Sets flight speed

  setspawn:
    description: Sets spawnpoint

  spawn:
    description: Teleports to spawn

  rules:
    description: Shows rules
    aliases:
      - rule

  nextclear:
    aliases:
      - nextlag
    description: Shows when next clear lag

  announce:
    aliases:
      - ann
      - announcement
    description: Announces a message to the server

  discord:
    description: Links our discord

  rank:
    description: Provides rank commands

  ban:
    description: Ban a player
    usage: /ban [-s] [-ip] <player> <reason>
  unban:
    description: Unban a player
    usage: /unban <player>
  banlist:
    description: List banned players
    usage: /banlist