name: KeeleUniWars
version: '${project.version}'
main: dev.joeyfoxo.keeleuniwars.KeeleUniWars
api-version: 1.19
authors: [ Joey ]
description: Just Another Furry Walls
website: https://joeyfox.dev

depend:
  - KeeleCore
  - FastAsyncWorldEdit