name: Deploy to VPS

on:
  push:
    branches: [development, master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H 49.13.78.86 >> ~/.ssh/known_hosts

    - name: Deploy to VPS
      run: |
        BRANCH="${GITHUB_REF##*/}"
        echo "Deploying branch: $BRANCH"
        if [[ "$BRANCH" == "development" ]]; then
          ssh root@49.13.78.86 "cd /root/LiveServer/GitHub && git pull origin development && ./deploy-development.sh \$(cat deploy.txt)"
        elif [[ "$BRANCH" == "master" ]]; then
          ssh root@49.13.78.86 "cd /root/LiveServer/GitHub && git pull origin master && ./deploy-master.sh \$(cat deploy.txt)"
        else
          echo "Unsupported branch: $BRANCH"
          exit 1
        fi
